name: Build esp_wifi_repeater (ESP8266 SDK)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make unrar-free autoconf automake libtool gcc g++ gperf flex bison texinfo gawk ncurses-dev libexpat-dev python3 python3-dev python3-pip git wget help2man gperf unzip bash
          sudo ln -sf /usr/bin/python3 /usr/bin/python
          sudo ln -sf /bin/bash /usr/bin/bash || true
          bash --version
          python --version

      - name: Get esp-open-sdk
        run: |
          git clone --recursive https://github.com/pfalcon/esp-open-sdk.git
          cd esp-open-sdk
          export BASH=/bin/bash
          export CONFIG_SHELL=/bin/bash
          export SHELL=/bin/bash
          echo "Using bash:" $(/bin/bash --version | head -n 1)
          make STANDALONE=y

      - name: Build firmware
        run: |
          export PATH=$PWD/esp-open-sdk/xtensa-lx106-elf/bin:$PATH
          make clean
          make

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-bin
          path: |
            *.bin
            firmware/*.bin
